org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties - check current values at https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.catting
archives_base_name=creativestash

# Dependencies
fabric_api_version=0.155.2+26.2
